"""Refactor models

Revision ID: 281733ab5ed1
Revises: 3a2b1c4d5e6f
Create Date: 2026-01-19 23:07:14.229524+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel desteği


# Revision identifiers, used by Alembic.
revision: str = '281733ab5ed1'
down_revision: Union[str, None] = '3a2b1c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Migration'ı uygula."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.alter_column('importance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Migration'ı geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.alter_column('importance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###











